/*
 * ScratchRobin
 * Copyright (c) 2025-2026 Dalton Calford
 *
 * Licensed under the Initial Developer's Public License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 * https://www.firebirdsql.org/en/initial-developer-s-public-license-version-1-0/
 */
#include "ddl_preview_dialog.h"

#include "diagram/forward_engineer.h"
#include "ui/diagram_model.h"

#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/choice.h>
#include <wx/clipbrd.h>
#include <wx/file.h>
#include <wx/filedlg.h>
#include <wx/msgdlg.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>

namespace scratchrobin {

wxBEGIN_EVENT_TABLE(DdlPreviewDialog, wxDialog)
    EVT_CHOICE(wxID_ANY, DdlPreviewDialog::OnTargetChanged)
wxEND_EVENT_TABLE()

DdlPreviewDialog::DdlPreviewDialog(wxWindow* parent, const DiagramModel& model)
    : wxDialog(parent, wxID_ANY, "DDL Preview", wxDefaultPosition, wxSize(800, 600)),
      model_(model) {
    BuildLayout();
    GenerateDdl();
}

void DdlPreviewDialog::BuildLayout() {
    auto* root = new wxBoxSizer(wxVERTICAL);
    
    // Target database selection
    auto* targetSizer = new wxBoxSizer(wxHORIZONTAL);
    targetSizer->Add(new wxStaticText(this, wxID_ANY, "Target Database:"), 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, 8);
    target_choice_ = new wxChoice(this, wxID_ANY);
    target_choice_->Append("ScratchBird");
    target_choice_->Append("PostgreSQL");
    target_choice_->Append("MySQL");
    target_choice_->Append("Firebird");
    target_choice_->SetSelection(0);
    targetSizer->Add(target_choice_, 1, wxEXPAND);
    root->Add(targetSizer, 0, wxEXPAND | wxALL, 12);
    
    // Options
    auto* optionsSizer = new wxBoxSizer(wxHORIZONTAL);
    include_drops_chk_ = new wxCheckBox(this, wxID_ANY, "Include DROP statements");
    include_comments_chk_ = new wxCheckBox(this, wxID_ANY, "Include comments");
    include_comments_chk_->SetValue(true);
    optionsSizer->Add(include_drops_chk_, 0, wxRIGHT, 16);
    optionsSizer->Add(include_comments_chk_, 0);
    optionsSizer->AddStretchSpacer(1);
    root->Add(optionsSizer, 0, wxEXPAND | wxLEFT | wxRIGHT | wxBOTTOM, 12);
    
    // DDL text area
    ddl_text_ = new wxTextCtrl(this, wxID_ANY, "", wxDefaultPosition, wxDefaultSize,
                               wxTE_MULTILINE | wxTE_READONLY | wxHSCROLL);
    ddl_text_->SetFont(wxFont(10, wxFONTFAMILY_TELETYPE, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL));
    root->Add(ddl_text_, 1, wxEXPAND | wxLEFT | wxRIGHT | wxBOTTOM, 12);
    
    // Buttons
    auto* btnSizer = new wxBoxSizer(wxHORIZONTAL);
    btnSizer->Add(new wxButton(this, wxID_ANY, "Copy to Clipboard"), 0, wxRIGHT, 6);
    btnSizer->Add(new wxButton(this, wxID_ANY, "Save to File..."), 0, wxRIGHT, 6);
    btnSizer->AddStretchSpacer(1);
    btnSizer->Add(new wxButton(this, wxID_CANCEL, "Close"), 0, wxRIGHT, 6);
    btnSizer->Add(new wxButton(this, wxID_OK, "Execute..."), 0);
    root->Add(btnSizer, 0, wxEXPAND | wxALL, 12);
    
    SetSizer(root);
    
    // Bind button events
    Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
        auto* btn = dynamic_cast<wxButton*>(evt.GetEventObject());
        if (btn) {
            wxString label = btn->GetLabel();
            if (label.Contains("Copy")) {
                OnCopy(evt);
            } else if (label.Contains("Save")) {
                OnSave(evt);
            } else if (label.Contains("Execute")) {
                OnExecute(evt);
            }
        }
    });
}

void DdlPreviewDialog::SetTarget(DdlTarget target) {
    current_target_ = target;
    if (target_choice_) {
        target_choice_->SetSelection(static_cast<int>(target));
    }
    GenerateDdl();
}

void DdlPreviewDialog::GenerateDdl() {
    if (!ddl_text_) return;
    
    std::string backend;
    switch (current_target_) {
        case DdlTarget::PostgreSQL: backend = "postgresql"; break;
        case DdlTarget::MySQL: backend = "mysql"; break;
        case DdlTarget::Firebird: backend = "firebird"; break;
        case DdlTarget::ScratchBird:
        default: backend = "scratchbird"; break;
    }
    
    diagram::ForwardEngineerOptions options;
    options.drop_existing = include_drops_chk_->GetValue();
    options.include_comments = include_comments_chk_->GetValue();
    
    auto result = diagram::DdlPreview::GeneratePreview(model_, backend, options);
    
    std::string ddl;
    if (include_comments_chk_->GetValue()) {
        ddl = "-- Generated DDL for " + target_choice_->GetStringSelection() + "\n" +
              "-- Generated by ScratchRobin\n" +
              "-- Tables: " + std::to_string(result.table_count) + 
              ", Indexes: " + std::to_string(result.index_count) +
              ", Constraints: " + std::to_string(result.constraint_count) + "\n\n";
    }
    ddl += result.ddl;
    
    ddl_text_->SetValue(ddl);
}

std::string DdlPreviewDialog::GetDdl() const {
    return ddl_text_ ? ddl_text_->GetValue().ToStdString() : "";
}

DdlTarget DdlPreviewDialog::GetTarget() const {
    return current_target_;
}

void DdlPreviewDialog::OnTargetChanged(wxCommandEvent&) {
    current_target_ = static_cast<DdlTarget>(target_choice_->GetSelection());
    GenerateDdl();
}

void DdlPreviewDialog::OnCopy(wxCommandEvent&) {
    if (wxTheClipboard->Open()) {
        wxTheClipboard->SetData(new wxTextDataObject(ddl_text_->GetValue()));
        wxTheClipboard->Close();
        wxMessageBox("DDL copied to clipboard.", "Copied", wxOK | wxICON_INFORMATION, this);
    }
}

void DdlPreviewDialog::OnSave(wxCommandEvent&) {
    wxFileDialog dialog(this, "Save DDL", "", "schema.sql", 
                        "SQL files (*.sql)|*.sql|All files (*.*)|*.*",
                        wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
    if (dialog.ShowModal() == wxID_OK) {
        wxFile file(dialog.GetPath(), wxFile::write);
        if (file.IsOpened()) {
            file.Write(ddl_text_->GetValue());
            file.Close();
            wxMessageBox("DDL saved successfully.", "Saved", wxOK | wxICON_INFORMATION, this);
        }
    }
}

void DdlPreviewDialog::OnExecute(wxCommandEvent&) {
    wxMessageBox("Execute functionality would open an SQL Editor with this DDL.\n"
                 "You can copy the DDL and paste it into an SQL Editor to execute.",
                 "Execute DDL", wxOK | wxICON_INFORMATION, this);
}

} // namespace scratchrobin
