#ifndef SCRATCHROBIN_MENU_IDS_H
#define SCRATCHROBIN_MENU_IDS_H

#include <wx/defs.h>

namespace scratchrobin {

constexpr int ID_MENU_NEW_SQL_EDITOR = wxID_HIGHEST + 500;
constexpr int ID_MENU_NEW_DIAGRAM = wxID_HIGHEST + 501;
constexpr int ID_MENU_MONITORING = wxID_HIGHEST + 502;
constexpr int ID_MENU_USERS_ROLES = wxID_HIGHEST + 503;
constexpr int ID_MENU_HELP_WINDOW = wxID_HIGHEST + 504;
constexpr int ID_MENU_HELP_COMMAND = wxID_HIGHEST + 505;
constexpr int ID_MENU_HELP_LANGUAGE = wxID_HIGHEST + 506;

constexpr int ID_SQL_RUN = wxID_HIGHEST + 510;
constexpr int ID_SQL_CANCEL = wxID_HIGHEST + 511;
constexpr int ID_SQL_EXPORT_CSV = wxID_HIGHEST + 512;
constexpr int ID_SQL_EXPORT_JSON = wxID_HIGHEST + 513;

constexpr int ID_CONN_SERVER_CREATE = wxID_HIGHEST + 520;
constexpr int ID_CONN_SERVER_CONNECT = wxID_HIGHEST + 521;
constexpr int ID_CONN_SERVER_DISCONNECT = wxID_HIGHEST + 522;
constexpr int ID_CONN_SERVER_DROP = wxID_HIGHEST + 523;
constexpr int ID_CONN_SERVER_REMOVE = wxID_HIGHEST + 524;

constexpr int ID_CONN_CLUSTER_CREATE = wxID_HIGHEST + 530;
constexpr int ID_CONN_CLUSTER_CONNECT = wxID_HIGHEST + 531;
constexpr int ID_CONN_CLUSTER_DISCONNECT = wxID_HIGHEST + 532;
constexpr int ID_CONN_CLUSTER_DROP = wxID_HIGHEST + 533;
constexpr int ID_CONN_CLUSTER_REMOVE = wxID_HIGHEST + 534;

constexpr int ID_CONN_DATABASE_CREATE = wxID_HIGHEST + 540;
constexpr int ID_CONN_DATABASE_CONNECT = wxID_HIGHEST + 541;
constexpr int ID_CONN_DATABASE_DISCONNECT = wxID_HIGHEST + 542;
constexpr int ID_CONN_DATABASE_DROP = wxID_HIGHEST + 543;

constexpr int ID_CONN_PROJECT_CREATE = wxID_HIGHEST + 550;
constexpr int ID_CONN_PROJECT_CONNECT = wxID_HIGHEST + 551;
constexpr int ID_CONN_PROJECT_DISCONNECT = wxID_HIGHEST + 552;
constexpr int ID_CONN_PROJECT_DROP = wxID_HIGHEST + 553;

constexpr int ID_CONN_DIAGRAM_CREATE_ERD = wxID_HIGHEST + 560;
constexpr int ID_CONN_DIAGRAM_CREATE_FLOW = wxID_HIGHEST + 561;
constexpr int ID_CONN_DIAGRAM_CREATE_UML = wxID_HIGHEST + 562;
constexpr int ID_CONN_DIAGRAM_OPEN = wxID_HIGHEST + 563;
constexpr int ID_CONN_DIAGRAM_DROP = wxID_HIGHEST + 564;

constexpr int ID_CONN_GIT_CONFIGURE = wxID_HIGHEST + 570;
constexpr int ID_CONN_GIT_CONNECT = wxID_HIGHEST + 571;
constexpr int ID_CONN_GIT_OPEN = wxID_HIGHEST + 572;
constexpr int ID_CONN_GIT_STATUS = wxID_HIGHEST + 573;
constexpr int ID_CONN_GIT_PULL = wxID_HIGHEST + 574;
constexpr int ID_CONN_GIT_PUSH = wxID_HIGHEST + 575;

} // namespace scratchrobin

#endif // SCRATCHROBIN_MENU_IDS_H
